import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Thierry Dev Portifolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <link
        rel="preload"
        href="/src/styles/fonts/Valorax-lg25V.otf"
        as="font"
        type="font/otf"
      />
      <link rel="shortcut icon" href="/favicon.ico" />
      <body className={inter.className} suppressHydrationWarning>
        {children}
      </body>
    </html>
  )
}
